# .github/workflows/pacman.yml
name: 🟡 Pac-Man Animation

on:
  schedule:
    - cron: "30 0 * * *"  # roda todo dia às 00h30 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Gerar pacman.svg baseado no seu gráfico
        uses: abozanona/pacman-contribution-graph@v1.2
        with:
          user: Diogenes28
          output_file: dist/pacman.svg

      - name: Publicar na branch output
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output
          keep_files: true
