name: 🟡 Pac-Man Animation

on:
  schedule:
    - cron: '0 2 * * *'  # Executa todo dia às 2h da manhã UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar animação Pac-Man
        uses: abozanona/contribution-pacman@main

      - name: Criar pasta dist e mover arquivo
        run: |
          mkdir -p dist
          mv pacman.svg dist/

      - name: Publicar na branch output
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
