name: 👾 Pac-Man Animation
 
on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Gerar animação do Pac-Man
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Diogenes28
          outputs: |
            dist/pacman.svg

      - name: Enviar para a branch `output`
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
